// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Helpful_Tools_for_Microsoft_AX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidHelpful_Tools_for_Microsoft_AXPackageString = "707701dc-c5d9-4d96-95de-4c5210372b7d";
        public static Guid guidHelpful_Tools_for_Microsoft_AXPackage = new Guid(guidHelpful_Tools_for_Microsoft_AXPackageString);

        public const string guidHelpful_Tools_for_Microsoft_AXPackageCmdSetString = "4912c311-c32b-43eb-af7b-995f102e7317";
        public static Guid guidHelpful_Tools_for_Microsoft_AXPackageCmdSet = new Guid(guidHelpful_Tools_for_Microsoft_AXPackageCmdSetString);

        public const string guidImagesString = "45941dbb-bba8-4aa7-a3eb-7a8e10443899";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LabelTranslatorCommandId = 0x0100;
        public const int cmdidLabelSearchCommand = 0x0101;
        public const int cmdidToolManagerCommand = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}